# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: updatestubproxy.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='updatestubproxy.proto',
  package='updatestubproxy',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x15updatestubproxy.proto\x12\x0fupdatestubproxy\"+\n\x0fRegisterRequest\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0c\n\x04port\x18\x02 \x01(\t\"C\n\x10RegisterResponse\x12/\n\nreturncode\x18\x01 \x01(\x0e\x32\x1b.updatestubproxy.ReturnCode\"!\n\x0b\x45valRequest\x12\x12\n\nexpression\x18\x01 \x01(\t\"O\n\x0c\x45valResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12/\n\nreturncode\x18\x02 \x01(\x0e\x32\x1b.updatestubproxy.ReturnCode\"\r\n\x0bPingRequest\"O\n\x0cPingResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12/\n\nreturncode\x18\x02 \x01(\x0e\x32\x1b.updatestubproxy.ReturnCode\"6\n\rUploadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\x12\x13\n\x0b\x66ilecontent\x18\x02 \x01(\t\"#\n\x0f\x44ownloadRequest\x12\x10\n\x08\x66ilename\x18\x01 \x01(\t\"A\n\x0eUploadResponse\x12/\n\nreturncode\x18\x01 \x01(\x0e\x32\x1b.updatestubproxy.ReturnCode\"j\n\x10\x44ownloadResponse\x12/\n\nreturncode\x18\x01 \x01(\x0e\x32\x1b.updatestubproxy.ReturnCode\x12\x10\n\x08\x66ilename\x18\x02 \x01(\t\x12\x13\n\x0b\x66ilecontent\x18\x03 \x01(\t*&\n\nReturnCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32\x93\x03\n\x0fUpdateStubProxy\x12Q\n\x08register\x12 .updatestubproxy.RegisterRequest\x1a!.updatestubproxy.RegisterResponse\"\x00\x12\x46\n\x05\x65val_\x12\x1c.updatestubproxy.EvalRequest\x1a\x1d.updatestubproxy.EvalResponse\"\x00\x12\x45\n\x04ping\x12\x1c.updatestubproxy.PingRequest\x1a\x1d.updatestubproxy.PingResponse\"\x00\x12K\n\x06upload\x12\x1e.updatestubproxy.UploadRequest\x1a\x1f.updatestubproxy.UploadResponse\"\x00\x12Q\n\x08\x64ownload\x12 .updatestubproxy.DownloadRequest\x1a!.updatestubproxy.DownloadResponse\"\x00\x62\x06proto3')
)

_RETURNCODE = _descriptor.EnumDescriptor(
  name='ReturnCode',
  full_name='updatestubproxy.ReturnCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=636,
  serialized_end=674,
)
_sym_db.RegisterEnumDescriptor(_RETURNCODE)

ReturnCode = enum_type_wrapper.EnumTypeWrapper(_RETURNCODE)
SUCCESS = 0
FAILURE = 1



_REGISTERREQUEST = _descriptor.Descriptor(
  name='RegisterRequest',
  full_name='updatestubproxy.RegisterRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='updatestubproxy.RegisterRequest.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='port', full_name='updatestubproxy.RegisterRequest.port', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=42,
  serialized_end=85,
)


_REGISTERRESPONSE = _descriptor.Descriptor(
  name='RegisterResponse',
  full_name='updatestubproxy.RegisterResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='returncode', full_name='updatestubproxy.RegisterResponse.returncode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=87,
  serialized_end=154,
)


_EVALREQUEST = _descriptor.Descriptor(
  name='EvalRequest',
  full_name='updatestubproxy.EvalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='expression', full_name='updatestubproxy.EvalRequest.expression', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=156,
  serialized_end=189,
)


_EVALRESPONSE = _descriptor.Descriptor(
  name='EvalResponse',
  full_name='updatestubproxy.EvalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='updatestubproxy.EvalResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returncode', full_name='updatestubproxy.EvalResponse.returncode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=191,
  serialized_end=270,
)


_PINGREQUEST = _descriptor.Descriptor(
  name='PingRequest',
  full_name='updatestubproxy.PingRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=272,
  serialized_end=285,
)


_PINGRESPONSE = _descriptor.Descriptor(
  name='PingResponse',
  full_name='updatestubproxy.PingResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='updatestubproxy.PingResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returncode', full_name='updatestubproxy.PingResponse.returncode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=287,
  serialized_end=366,
)


_UPLOADREQUEST = _descriptor.Descriptor(
  name='UploadRequest',
  full_name='updatestubproxy.UploadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='updatestubproxy.UploadRequest.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filecontent', full_name='updatestubproxy.UploadRequest.filecontent', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=368,
  serialized_end=422,
)


_DOWNLOADREQUEST = _descriptor.Descriptor(
  name='DownloadRequest',
  full_name='updatestubproxy.DownloadRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='filename', full_name='updatestubproxy.DownloadRequest.filename', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=424,
  serialized_end=459,
)


_UPLOADRESPONSE = _descriptor.Descriptor(
  name='UploadResponse',
  full_name='updatestubproxy.UploadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='returncode', full_name='updatestubproxy.UploadResponse.returncode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=461,
  serialized_end=526,
)


_DOWNLOADRESPONSE = _descriptor.Descriptor(
  name='DownloadResponse',
  full_name='updatestubproxy.DownloadResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='returncode', full_name='updatestubproxy.DownloadResponse.returncode', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filename', full_name='updatestubproxy.DownloadResponse.filename', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='filecontent', full_name='updatestubproxy.DownloadResponse.filecontent', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=528,
  serialized_end=634,
)

_REGISTERRESPONSE.fields_by_name['returncode'].enum_type = _RETURNCODE
_EVALRESPONSE.fields_by_name['returncode'].enum_type = _RETURNCODE
_PINGRESPONSE.fields_by_name['returncode'].enum_type = _RETURNCODE
_UPLOADRESPONSE.fields_by_name['returncode'].enum_type = _RETURNCODE
_DOWNLOADRESPONSE.fields_by_name['returncode'].enum_type = _RETURNCODE
DESCRIPTOR.message_types_by_name['RegisterRequest'] = _REGISTERREQUEST
DESCRIPTOR.message_types_by_name['RegisterResponse'] = _REGISTERRESPONSE
DESCRIPTOR.message_types_by_name['EvalRequest'] = _EVALREQUEST
DESCRIPTOR.message_types_by_name['EvalResponse'] = _EVALRESPONSE
DESCRIPTOR.message_types_by_name['PingRequest'] = _PINGREQUEST
DESCRIPTOR.message_types_by_name['PingResponse'] = _PINGRESPONSE
DESCRIPTOR.message_types_by_name['UploadRequest'] = _UPLOADREQUEST
DESCRIPTOR.message_types_by_name['DownloadRequest'] = _DOWNLOADREQUEST
DESCRIPTOR.message_types_by_name['UploadResponse'] = _UPLOADRESPONSE
DESCRIPTOR.message_types_by_name['DownloadResponse'] = _DOWNLOADRESPONSE
DESCRIPTOR.enum_types_by_name['ReturnCode'] = _RETURNCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

RegisterRequest = _reflection.GeneratedProtocolMessageType('RegisterRequest', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERREQUEST,
  '__module__' : 'updatestubproxy_pb2'
  # @@protoc_insertion_point(class_scope:updatestubproxy.RegisterRequest)
  })
_sym_db.RegisterMessage(RegisterRequest)

RegisterResponse = _reflection.GeneratedProtocolMessageType('RegisterResponse', (_message.Message,), {
  'DESCRIPTOR' : _REGISTERRESPONSE,
  '__module__' : 'updatestubproxy_pb2'
  # @@protoc_insertion_point(class_scope:updatestubproxy.RegisterResponse)
  })
_sym_db.RegisterMessage(RegisterResponse)

EvalRequest = _reflection.GeneratedProtocolMessageType('EvalRequest', (_message.Message,), {
  'DESCRIPTOR' : _EVALREQUEST,
  '__module__' : 'updatestubproxy_pb2'
  # @@protoc_insertion_point(class_scope:updatestubproxy.EvalRequest)
  })
_sym_db.RegisterMessage(EvalRequest)

EvalResponse = _reflection.GeneratedProtocolMessageType('EvalResponse', (_message.Message,), {
  'DESCRIPTOR' : _EVALRESPONSE,
  '__module__' : 'updatestubproxy_pb2'
  # @@protoc_insertion_point(class_scope:updatestubproxy.EvalResponse)
  })
_sym_db.RegisterMessage(EvalResponse)

PingRequest = _reflection.GeneratedProtocolMessageType('PingRequest', (_message.Message,), {
  'DESCRIPTOR' : _PINGREQUEST,
  '__module__' : 'updatestubproxy_pb2'
  # @@protoc_insertion_point(class_scope:updatestubproxy.PingRequest)
  })
_sym_db.RegisterMessage(PingRequest)

PingResponse = _reflection.GeneratedProtocolMessageType('PingResponse', (_message.Message,), {
  'DESCRIPTOR' : _PINGRESPONSE,
  '__module__' : 'updatestubproxy_pb2'
  # @@protoc_insertion_point(class_scope:updatestubproxy.PingResponse)
  })
_sym_db.RegisterMessage(PingResponse)

UploadRequest = _reflection.GeneratedProtocolMessageType('UploadRequest', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADREQUEST,
  '__module__' : 'updatestubproxy_pb2'
  # @@protoc_insertion_point(class_scope:updatestubproxy.UploadRequest)
  })
_sym_db.RegisterMessage(UploadRequest)

DownloadRequest = _reflection.GeneratedProtocolMessageType('DownloadRequest', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADREQUEST,
  '__module__' : 'updatestubproxy_pb2'
  # @@protoc_insertion_point(class_scope:updatestubproxy.DownloadRequest)
  })
_sym_db.RegisterMessage(DownloadRequest)

UploadResponse = _reflection.GeneratedProtocolMessageType('UploadResponse', (_message.Message,), {
  'DESCRIPTOR' : _UPLOADRESPONSE,
  '__module__' : 'updatestubproxy_pb2'
  # @@protoc_insertion_point(class_scope:updatestubproxy.UploadResponse)
  })
_sym_db.RegisterMessage(UploadResponse)

DownloadResponse = _reflection.GeneratedProtocolMessageType('DownloadResponse', (_message.Message,), {
  'DESCRIPTOR' : _DOWNLOADRESPONSE,
  '__module__' : 'updatestubproxy_pb2'
  # @@protoc_insertion_point(class_scope:updatestubproxy.DownloadResponse)
  })
_sym_db.RegisterMessage(DownloadResponse)



_UPDATESTUBPROXY = _descriptor.ServiceDescriptor(
  name='UpdateStubProxy',
  full_name='updatestubproxy.UpdateStubProxy',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=677,
  serialized_end=1080,
  methods=[
  _descriptor.MethodDescriptor(
    name='register',
    full_name='updatestubproxy.UpdateStubProxy.register',
    index=0,
    containing_service=None,
    input_type=_REGISTERREQUEST,
    output_type=_REGISTERRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='eval_',
    full_name='updatestubproxy.UpdateStubProxy.eval_',
    index=1,
    containing_service=None,
    input_type=_EVALREQUEST,
    output_type=_EVALRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='ping',
    full_name='updatestubproxy.UpdateStubProxy.ping',
    index=2,
    containing_service=None,
    input_type=_PINGREQUEST,
    output_type=_PINGRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='upload',
    full_name='updatestubproxy.UpdateStubProxy.upload',
    index=3,
    containing_service=None,
    input_type=_UPLOADREQUEST,
    output_type=_UPLOADRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='download',
    full_name='updatestubproxy.UpdateStubProxy.download',
    index=4,
    containing_service=None,
    input_type=_DOWNLOADREQUEST,
    output_type=_DOWNLOADRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_UPDATESTUBPROXY)

DESCRIPTOR.services_by_name['UpdateStubProxy'] = _UPDATESTUBPROXY

# @@protoc_insertion_point(module_scope)
