# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pyliveupdate.grpc.updatestub_pb2 as updatestub__pb2


class RemoteEvalStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.eval_ = channel.unary_unary(
        '/updatestub.RemoteEval/eval_',
        request_serializer=updatestub__pb2.EvalRequest.SerializeToString,
        response_deserializer=updatestub__pb2.EvalResponse.FromString,
        )
    self.ping = channel.unary_unary(
        '/updatestub.RemoteEval/ping',
        request_serializer=updatestub__pb2.PingRequest.SerializeToString,
        response_deserializer=updatestub__pb2.PingResponse.FromString,
        )


class RemoteEvalServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def eval_(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RemoteEvalServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'eval_': grpc.unary_unary_rpc_method_handler(
          servicer.eval_,
          request_deserializer=updatestub__pb2.EvalRequest.FromString,
          response_serializer=updatestub__pb2.EvalResponse.SerializeToString,
      ),
      'ping': grpc.unary_unary_rpc_method_handler(
          servicer.ping,
          request_deserializer=updatestub__pb2.PingRequest.FromString,
          response_serializer=updatestub__pb2.PingResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'updatestub.RemoteEval', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
