# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pyliveupdate.grpc.updatestubproxy_pb2 as updatestubproxy__pb2


class UpdateStubProxyStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.register = channel.unary_unary(
        '/updatestubproxy.UpdateStubProxy/register',
        request_serializer=updatestubproxy__pb2.RegisterRequest.SerializeToString,
        response_deserializer=updatestubproxy__pb2.RegisterResponse.FromString,
        )
    self.eval_ = channel.unary_unary(
        '/updatestubproxy.UpdateStubProxy/eval_',
        request_serializer=updatestubproxy__pb2.EvalRequest.SerializeToString,
        response_deserializer=updatestubproxy__pb2.EvalResponse.FromString,
        )
    self.ping = channel.unary_unary(
        '/updatestubproxy.UpdateStubProxy/ping',
        request_serializer=updatestubproxy__pb2.PingRequest.SerializeToString,
        response_deserializer=updatestubproxy__pb2.PingResponse.FromString,
        )
    self.upload = channel.unary_unary(
        '/updatestubproxy.UpdateStubProxy/upload',
        request_serializer=updatestubproxy__pb2.UploadRequest.SerializeToString,
        response_deserializer=updatestubproxy__pb2.UploadResponse.FromString,
        )
    self.download = channel.unary_unary(
        '/updatestubproxy.UpdateStubProxy/download',
        request_serializer=updatestubproxy__pb2.DownloadRequest.SerializeToString,
        response_deserializer=updatestubproxy__pb2.DownloadResponse.FromString,
        )


class UpdateStubProxyServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def register(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def eval_(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def ping(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def upload(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')

  def download(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_UpdateStubProxyServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'register': grpc.unary_unary_rpc_method_handler(
          servicer.register,
          request_deserializer=updatestubproxy__pb2.RegisterRequest.FromString,
          response_serializer=updatestubproxy__pb2.RegisterResponse.SerializeToString,
      ),
      'eval_': grpc.unary_unary_rpc_method_handler(
          servicer.eval_,
          request_deserializer=updatestubproxy__pb2.EvalRequest.FromString,
          response_serializer=updatestubproxy__pb2.EvalResponse.SerializeToString,
      ),
      'ping': grpc.unary_unary_rpc_method_handler(
          servicer.ping,
          request_deserializer=updatestubproxy__pb2.PingRequest.FromString,
          response_serializer=updatestubproxy__pb2.PingResponse.SerializeToString,
      ),
      'upload': grpc.unary_unary_rpc_method_handler(
          servicer.upload,
          request_deserializer=updatestubproxy__pb2.UploadRequest.FromString,
          response_serializer=updatestubproxy__pb2.UploadResponse.SerializeToString,
      ),
      'download': grpc.unary_unary_rpc_method_handler(
          servicer.download,
          request_deserializer=updatestubproxy__pb2.DownloadRequest.FromString,
          response_serializer=updatestubproxy__pb2.DownloadResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'updatestubproxy.UpdateStubProxy', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
