# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import pyliveupdate.grpc.updatestub_pb2 as updatestub__pb2


class RemoteEvalStub(object):
  # missing associated documentation comment in .proto file
  pass

  def __init__(self, channel):
    """Constructor.

    Args:
      channel: A grpc.Channel.
    """
    self.send_eval = channel.unary_unary(
        '/updatestub.RemoteEval/send_eval',
        request_serializer=updatestub__pb2.SendEvalRequest.SerializeToString,
        response_deserializer=updatestub__pb2.SendEvalResponse.FromString,
        )


class RemoteEvalServicer(object):
  # missing associated documentation comment in .proto file
  pass

  def send_eval(self, request, context):
    # missing associated documentation comment in .proto file
    pass
    context.set_code(grpc.StatusCode.UNIMPLEMENTED)
    context.set_details('Method not implemented!')
    raise NotImplementedError('Method not implemented!')


def add_RemoteEvalServicer_to_server(servicer, server):
  rpc_method_handlers = {
      'send_eval': grpc.unary_unary_rpc_method_handler(
          servicer.send_eval,
          request_deserializer=updatestub__pb2.SendEvalRequest.FromString,
          response_serializer=updatestub__pb2.SendEvalResponse.SerializeToString,
      ),
  }
  generic_handler = grpc.method_handlers_generic_handler(
      'updatestub.RemoteEval', rpc_method_handlers)
  server.add_generic_rpc_handlers((generic_handler,))
