# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: updatestub.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='updatestub.proto',
  package='updatestub',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x10updatestub.proto\x12\nupdatestub\"%\n\x0fSendEvalRequest\x12\x12\n\nexpression\x18\x01 \x01(\t\"N\n\x10SendEvalResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\x12*\n\nreturncode\x18\x02 \x01(\x0e\x32\x16.updatestub.ReturnCode*&\n\nReturnCode\x12\x0b\n\x07SUCCESS\x10\x00\x12\x0b\n\x07\x46\x41ILURE\x10\x01\x32V\n\nRemoteEval\x12H\n\tsend_eval\x12\x1b.updatestub.SendEvalRequest\x1a\x1c.updatestub.SendEvalResponse\"\x00\x62\x06proto3')
)

_RETURNCODE = _descriptor.EnumDescriptor(
  name='ReturnCode',
  full_name='updatestub.ReturnCode',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='SUCCESS', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='FAILURE', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=151,
  serialized_end=189,
)
_sym_db.RegisterEnumDescriptor(_RETURNCODE)

ReturnCode = enum_type_wrapper.EnumTypeWrapper(_RETURNCODE)
SUCCESS = 0
FAILURE = 1



_SENDEVALREQUEST = _descriptor.Descriptor(
  name='SendEvalRequest',
  full_name='updatestub.SendEvalRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='expression', full_name='updatestub.SendEvalRequest.expression', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=69,
)


_SENDEVALRESPONSE = _descriptor.Descriptor(
  name='SendEvalResponse',
  full_name='updatestub.SendEvalResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='updatestub.SendEvalResponse.result', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='returncode', full_name='updatestub.SendEvalResponse.returncode', index=1,
      number=2, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=71,
  serialized_end=149,
)

_SENDEVALRESPONSE.fields_by_name['returncode'].enum_type = _RETURNCODE
DESCRIPTOR.message_types_by_name['SendEvalRequest'] = _SENDEVALREQUEST
DESCRIPTOR.message_types_by_name['SendEvalResponse'] = _SENDEVALRESPONSE
DESCRIPTOR.enum_types_by_name['ReturnCode'] = _RETURNCODE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

SendEvalRequest = _reflection.GeneratedProtocolMessageType('SendEvalRequest', (_message.Message,), {
  'DESCRIPTOR' : _SENDEVALREQUEST,
  '__module__' : 'updatestub_pb2'
  # @@protoc_insertion_point(class_scope:updatestub.SendEvalRequest)
  })
_sym_db.RegisterMessage(SendEvalRequest)

SendEvalResponse = _reflection.GeneratedProtocolMessageType('SendEvalResponse', (_message.Message,), {
  'DESCRIPTOR' : _SENDEVALRESPONSE,
  '__module__' : 'updatestub_pb2'
  # @@protoc_insertion_point(class_scope:updatestub.SendEvalResponse)
  })
_sym_db.RegisterMessage(SendEvalResponse)



_REMOTEEVAL = _descriptor.ServiceDescriptor(
  name='RemoteEval',
  full_name='updatestub.RemoteEval',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=191,
  serialized_end=277,
  methods=[
  _descriptor.MethodDescriptor(
    name='send_eval',
    full_name='updatestub.RemoteEval.send_eval',
    index=0,
    containing_service=None,
    input_type=_SENDEVALREQUEST,
    output_type=_SENDEVALRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_REMOTEEVAL)

DESCRIPTOR.services_by_name['RemoteEval'] = _REMOTEEVAL

# @@protoc_insertion_point(module_scope)
